apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: a4ai-backend
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        app: a4ai-backend
      annotations:
        # Scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        
        # Resource allocation
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
        
        # Networking
        run.googleapis.com/execution-environment: gen2
        
        # Security
        run.googleapis.com/sandbox: gvisor
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: a4ai-backend
        image: us-central1-docker.pkg.dev/a4ai-10bf3/a4ai-repo/a4ai-backend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: WORKERS
          value: "1"
        - name: HOST
          value: "0.0.0.0"
        - name: PYTHONPATH
          value: "/app"
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
