name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make education more accessible.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Who would benefit from it?
      placeholder: Describe the problem or need...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe alternatives...
      
  - type: dropdown
    id: impact
    attributes:
      label: Impact Area
      description: Which area would this feature primarily impact?
      options:
        - Student Experience
        - Educator Tools
        - Assessment System
        - Content Generation
        - Voice Interaction
        - Lesson Planning
        - Performance/Scalability
        - Security/Privacy
        - API/Integration
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking major use case
        - High - Significantly improves usability
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references about the feature request
